### ISSUE TITLE
an error in Usage:

### ISSUE THREAD

**Issue by traddo** [lucidrains/e2-tts-pytorch#2]
```

Traceback (most recent call last):
  File "/home/steven/work/dub_studio/e2tts.py", line 16, in <module>
    loss = duration_predictor(x, target_duration=duration)
  File "/opt/conda/envs/e2tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/e2tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: DurationPredictor.forward() got an unexpected keyword argument 'target_duration'

```

**Comment by lucidrains** [comment]
@traddo oops, try removing that kwarg

I'll update the readme later
